class QuizBrain {
  List<String> qusList = [
    "Which of the following pictures depict your attitude towards your goal?",
    "Which of the following pictures correctly depict your current state of mind?",
    "Which picture accurately shows your current breathing pattern?",
    "Touch your forehead. Do you feel sweat in your hands?",
    "With which picture do you relate the most while studying?",
    "Which picture correctly shows your sleeping schedule?",
    "How do you feel while studying?",
    "How do you feel about your future?",
    "Do you often feel angry without any proper reason?",
    "Do you frequently overreact to normal circumstances?",
    "Have you noticed any change in your eating behaviour? Say, eating more, or less than before.",
    "Have you ever felt so tired that you feel like giving up on everything?",
    "Do you have any energy left after completing your everyday chores?",
    "Do you have people around you with whom you can share your thoughts?",
    "Do you feel disconnected from your friends even after socialising on online social platforms?",
    "Have you noticed sudden weight gain over the past few months?",
    "If you are given a choice to get your favorite Mike Jorbans at the cost of not talking to a friend for a month, what will you choose?",
    "Do you like being around people?",
    "When you think about your past, do you remember stressful memories or the happy ones?",
    "What kind of dreams do you often have?",
    "Do you find yourself involved among the people’s discussion, or are you the one at the corner of the room?",
    "Are you hopeful towards your dreams?",
    "Do you find it difficult to work towards your goals without distractions?",
    "Do you often find yourself taking responsibility for your actions?",
  ];
  List<String> animationUrl = [
    "assets/animations/sad.riv",
    "assets/animations/man.riv",
    "assets/animations/breathe.riv",
    "assets/animations/breathe.riv",
    "assets/animations/phone.riv",
    "assets/animations/sleepy_guy.riv",
    "assets/animations/crying.riv",
    "assets/animations/hopeless.riv",
    "assets/animations/man.riv",
    "assets/animations/man.riv",
    "assets/animations/food.riv",
    "assets/animations/suicide.riv",
    "assets/animations/tired.riv",
    "assets/animations/group.riv",
    "assets/animations/screentime.riv",
    "assets/animations/man.riv",
    "assets/animations/shoes.riv",
    "assets/animations/man.riv",
    "assets/animations/sad.riv",
    "assets/animations/ghost.riv",
    "assets/animations/group.riv",
    "assets/animations/negative.riv",
    "assets/animations/phone.riv",
    "assets/animations/man.riv",
  ];
  List<String> yesUrl = [
    "assets/images/yes/q1yes.jpg",
    "assets/images/yes/q2yes.jpg",
    "assets/images/yes/q3yes.jpg",
    "assets/images/yes/q4yes.jpg",
    "assets/images/yes/q5yes.jpeg",
    "assets/images/yes/q6yes.jpeg",
    "assets/images/yes/q7yes.jpg",
    "assets/images/yes/q8yes.jpg",
    "assets/images/yes/q9yes.jpg",
    "assets/images/yes/q10yes.jpg",
    "assets/images/yes/q11yes.jpg",
    "assets/images/yes/q12yes.jpg",
    "assets/images/yes/q13yes.png",
    "assets/images/yes/q14yes.png",
    "assets/images/yes/q15yes.png",
    "assets/images/yes/q16yes.jpg",
    "assets/images/yes/q17yes.jpg",
    "assets/images/yes/q18yes.jpg",
    "assets/images/yes/q19yes.jpg",
    "assets/images/yes/q20yes.jpg",
    "assets/images/yes/q21yes.jpg",
    "assets/images/yes/q22yes.jpg",
    "assets/images/yes/q23yes.jpg",
    "assets/images/yes/q24yes.png",
  ];
  List<String> noUrl = [
    "assets/images/no/q1no.jpeg",
    "assets/images/no/q2no.jpeg",
    "assets/images/no/q3no.jpeg",
    "assets/images/no/q4no.jpeg",
    "assets/images/no/q5no.jpeg",
    "assets/images/no/q6no.jpeg",
    "assets/images/no/q7no.jpeg",
    "assets/images/no/q8no.jpeg",
    "assets/images/no/q9no.jpeg",
    "assets/images/no/q10no.jpeg",
    "assets/images/no/q11no.jpeg",
    "assets/images/no/q12no.jpeg",
    "assets/images/no/q13no.png",
    "assets/images/no/q14no.png",
    "assets/images/no/q15no.jpg",
    "assets/images/no/q16no.png",
    "assets/images/no/q17no.png",
    "assets/images/no/q18no.jpg",
    "assets/images/no/q19no.jpg",
    "assets/images/no/q20no.jpg",
    "assets/images/no/q21no.jpg",
    "assets/images/no/q22no.jpg",
    "assets/images/no/q23no.png",
    "assets/images/no/q24no.jpg",
  ];
  List<int> answers = [];
}
